//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MacssWeb.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Aims {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Aims() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MacssWeb.Resources.Aims", typeof(Aims).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   営業費用一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BusinessCost {
            get {
                return ResourceManager.GetString("BusinessCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   営業費用計上照合処理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BusinessCostCalculateCheck {
            get {
                return ResourceManager.GetString("BusinessCostCalculateCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   営業費用登録 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BusinessCostCreate {
            get {
                return ResourceManager.GetString("BusinessCostCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   営業費用データ作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BusinessCostDataMake {
            get {
                return ResourceManager.GetString("BusinessCostDataMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ［営業費用］　PC・勘定コード一括変更 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BusinessCostPcAccountingCode {
            get {
                return ResourceManager.GetString("BusinessCostPcAccountingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   請求明細データ作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DetailedRecording {
            get {
                return ResourceManager.GetString("DetailedRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ESP仕入引渡しデータ一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EpsPurchasingData {
            get {
                return ResourceManager.GetString("EpsPurchasingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ESP仕入引渡しデータ作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EpsPurchasingDataMake {
            get {
                return ResourceManager.GetString("EpsPurchasingDataMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ESP請求引渡しデータ一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EpsRequestData {
            get {
                return ResourceManager.GetString("EpsRequestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ESP請求引渡しデータ作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EpsRequestDataMake {
            get {
                return ResourceManager.GetString("EpsRequestDataMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ESP請求引渡しデータ作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EspClaimDelivery {
            get {
                return ResourceManager.GetString("EspClaimDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ESP請求引渡しデータ一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EspClaimDeliveryList {
            get {
                return ResourceManager.GetString("EspClaimDeliveryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ESP本社得意先マスタアップロード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EspCustomerMst {
            get {
                return ResourceManager.GetString("EspCustomerMst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ESP本社得意先マスタ一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EspCustomerMstList {
            get {
                return ResourceManager.GetString("EspCustomerMstList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ESPデータ変換マスタアップロード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EspDataConvMst {
            get {
                return ResourceManager.GetString("EspDataConvMst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ESPデータ変換マスタ一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EspDataConvMstList {
            get {
                return ResourceManager.GetString("EspDataConvMstList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ESP請求項目マスタアップロード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EspInvoiceitemMst {
            get {
                return ResourceManager.GetString("EspInvoiceitemMst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ESP請求項目マスタ一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EspInvoiceitemMstList {
            get {
                return ResourceManager.GetString("EspInvoiceitemMstList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ESP仕入引渡しデータ作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EspPurchaseDelivery {
            get {
                return ResourceManager.GetString("EspPurchaseDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ESP仕入引渡しデータ一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EspPurchaseDeliveryList {
            get {
                return ResourceManager.GetString("EspPurchaseDeliveryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ESP連携処理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EspRelation {
            get {
                return ResourceManager.GetString("EspRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ESP本社仕入先マスタアップロード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EspVendorMst {
            get {
                return ResourceManager.GetString("EspVendorMst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ESP本社仕入先マスタ一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EspVendorMstList {
            get {
                return ResourceManager.GetString("EspVendorMstList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fe注文データ作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FeOrderDataMake {
            get {
                return ResourceManager.GetString("FeOrderDataMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fe請求データ作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FeRequestDataMake {
            get {
                return ResourceManager.GetString("FeRequestDataMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   月次売上データ作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MonthlySalesDataMake {
            get {
                return ResourceManager.GetString("MonthlySalesDataMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実績明細引渡しデータ作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProgressDetailTraditionDataMake {
            get {
                return ResourceManager.GetString("ProgressDetailTraditionDataMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録仕入明細一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RegistrationPurchasingDetail {
            get {
                return ResourceManager.GetString("RegistrationPurchasingDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録仕入明細登録 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RegistrationPurchasingDetailCreate {
            get {
                return ResourceManager.GetString("RegistrationPurchasingDetailCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録請求明細一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RegistrationRequestDetail {
            get {
                return ResourceManager.GetString("RegistrationRequestDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録請求明細登録 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RegistrationRequestDetailCreate {
            get {
                return ResourceManager.GetString("RegistrationRequestDetailCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   請求明細一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RequestDetail {
            get {
                return ResourceManager.GetString("RequestDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   請求明細登録 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RequestDetailCreate {
            get {
                return ResourceManager.GetString("RequestDetailCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ［請求明細］　PCコード一括変更 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RequestDetailPcCode {
            get {
                return ResourceManager.GetString("RequestDetailPcCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   請求関連書類印刷 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RequestDocumentPrint {
            get {
                return ResourceManager.GetString("RequestDocumentPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   請求売上・仕入確定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RequestSalesStockFixed {
            get {
                return ResourceManager.GetString("RequestSalesStockFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   請求引渡しデータ作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RequestTraditionDataMake {
            get {
                return ResourceManager.GetString("RequestTraditionDataMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   売上計上処理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SalesRecording {
            get {
                return ResourceManager.GetString("SalesRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   売上伝票一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SalesSlip {
            get {
                return ResourceManager.GetString("SalesSlip", resourceCulture);
            }
        }
    }
}
