//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MacssWeb.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Application {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Application() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MacssWeb.Resources.Application", typeof(Application).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   AIMS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AimsAbbrName {
            get {
                return ResourceManager.GetString("AimsAbbrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   請求仕入 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AimsJpName {
            get {
                return ResourceManager.GetString("AimsJpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BASE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BaseAbbrName {
            get {
                return ResourceManager.GetString("BaseAbbrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   共通管理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BaseJpName {
            get {
                return ResourceManager.GetString("BaseJpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DCOS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DcosAbbrName {
            get {
                return ResourceManager.GetString("DcosAbbrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保管業務 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DcosJpName {
            get {
                return ResourceManager.GetString("DcosJpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FDASS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FdassAbbrName {
            get {
                return ResourceManager.GetString("FdassAbbrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fe保管請求 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FdassJpName {
            get {
                return ResourceManager.GetString("FdassJpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PATS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PatsAbbrName {
            get {
                return ResourceManager.GetString("PatsAbbrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   包装商品販売 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PatsJpName {
            get {
                return ResourceManager.GetString("PatsJpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   松本支社業務統合システム(MACSS) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SystemName {
            get {
                return ResourceManager.GetString("SystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TASS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TassAbbrName {
            get {
                return ResourceManager.GetString("TassAbbrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   運送業務 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TassJpName {
            get {
                return ResourceManager.GetString("TassJpName", resourceCulture);
            }
        }
    }
}
