//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MacssWeb.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ControlText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlText() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MacssWeb.Resources.ControlText", typeof(ControlText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   自動設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AutoSettings {
            get {
                return ResourceManager.GetString("AutoSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   戻る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一覧へ戻る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サブメニューへ戻る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BackToSubMenu {
            get {
                return ResourceManager.GetString("BackToSubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再アップロード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BackToUpload {
            get {
                return ResourceManager.GetString("BackToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   条件クリア に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConditionClear {
            get {
                return ResourceManager.GetString("ConditionClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   参照作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CopyExec {
            get {
                return ResourceManager.GetString("CopyExec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateExec {
            get {
                return ResourceManager.GetString("CreateExec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteExec {
            get {
                return ResourceManager.GetString("DeleteExec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditExec {
            get {
                return ResourceManager.GetString("EditExec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実行 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Execute {
            get {
                return ResourceManager.GetString("Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InputConfirm {
            get {
                return ResourceManager.GetString("InputConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   いいえ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   印刷 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   棚番変更 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RackChange {
            get {
                return ResourceManager.GetString("RackChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップロード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UploadConfirm {
            get {
                return ResourceManager.GetString("UploadConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取込 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UploadExec {
            get {
                return ResourceManager.GetString("UploadExec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   はい に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
