//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MacssWeb.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Dcos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dcos() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MacssWeb.Resources.Dcos", typeof(Dcos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   倉庫・保存期限一括変更 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string D011MainTitle {
            get {
                return ResourceManager.GetString("D011MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   在庫引当計画実施 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StockAllocationExecMainTitle {
            get {
                return ResourceManager.GetString("StockAllocationExecMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   在庫引当一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StockAllocationListMainTitle {
            get {
                return ResourceManager.GetString("StockAllocationListMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   在庫引当 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StockAllocationMainTitle {
            get {
                return ResourceManager.GetString("StockAllocationMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ピッキングリスト出力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StockAllocationPickingListOutputMainTitle {
            get {
                return ResourceManager.GetString("StockAllocationPickingListOutputMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   在庫引当計画実施済解除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StockAllocationPlanCancelMainTitle {
            get {
                return ResourceManager.GetString("StockAllocationPlanCancelMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   在庫引当確定解除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StockAllocationPlanFixCancelMainTitle {
            get {
                return ResourceManager.GetString("StockAllocationPlanFixCancelMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   在庫引当確定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StockAllocationPlanFixMainTitle {
            get {
                return ResourceManager.GetString("StockAllocationPlanFixMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   在庫自動引当 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StockAutoAllocationMainTitle {
            get {
                return ResourceManager.GetString("StockAutoAllocationMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   在庫データ一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StockMainTitle {
            get {
                return ResourceManager.GetString("StockMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   計画引当数変更 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StockPlanEditMainTitle {
            get {
                return ResourceManager.GetString("StockPlanEditMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   棚番変更 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StockRachChangeMainTitle {
            get {
                return ResourceManager.GetString("StockRachChangeMainTitle", resourceCulture);
            }
        }
    }
}
