//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MacssWeb.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MacssWeb.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   以下を参照作成します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CopyConfirm {
            get {
                return ResourceManager.GetString("CopyConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   参照作成処理を実行します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CopyReconfirm {
            get {
                return ResourceManager.GetString("CopyReconfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   参照作成しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CopySuccess {
            get {
                return ResourceManager.GetString("CopySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   以下を登録します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateConfirm {
            get {
                return ResourceManager.GetString("CreateConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録処理を実行します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateReconfirm {
            get {
                return ResourceManager.GetString("CreateReconfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateSuccess {
            get {
                return ResourceManager.GetString("CreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   以下を削除します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除処理を実行します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteReconfirm {
            get {
                return ResourceManager.GetString("DeleteReconfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   以下を更新します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditConfirm {
            get {
                return ResourceManager.GetString("EditConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新処理を実行します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditReconfirm {
            get {
                return ResourceManager.GetString("EditReconfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditSuccess {
            get {
                return ResourceManager.GetString("EditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   以下を発行します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IssueConfirm {
            get {
                return ResourceManager.GetString("IssueConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データ作成を完了しましたが、以下のデータはエラーのため作成できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MakeCompleteFailure {
            get {
                return ResourceManager.GetString("MakeCompleteFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データ作成を完了しましたが、以下のデータにエラーがありました。確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MakeCompleteFailureConfirm {
            get {
                return ResourceManager.GetString("MakeCompleteFailureConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データ作成を完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MakeCompleteSuccess {
            get {
                return ResourceManager.GetString("MakeCompleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   以下のデータを作成します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MakeConfirm {
            get {
                return ResourceManager.GetString("MakeConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データ作成処理を実行します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MakeReconfirm {
            get {
                return ResourceManager.GetString("MakeReconfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   以下の入力値で棚番変更します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RackChengeConfirm {
            get {
                return ResourceManager.GetString("RackChengeConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   棚番変更処理を実行します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RackChengeReconfirm {
            get {
                return ResourceManager.GetString("RackChengeReconfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力されている場合、入力された情報は破棄されます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransitionConfirm {
            get {
                return ResourceManager.GetString("TransitionConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取込を完了しましたが、以下のデータはエラーのため取込できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UploadCompleteFailure {
            get {
                return ResourceManager.GetString("UploadCompleteFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取込を完了しましたが、以下のデータにエラーがありました。確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UploadCompleteFailureConfirm {
            get {
                return ResourceManager.GetString("UploadCompleteFailureConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取込を完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UploadCompleteSuccess {
            get {
                return ResourceManager.GetString("UploadCompleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   以下のデータを取込ます。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UploadConfirm {
            get {
                return ResourceManager.GetString("UploadConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取込処理を実行します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UploadReconfirm {
            get {
                return ResourceManager.GetString("UploadReconfirm", resourceCulture);
            }
        }
    }
}
