//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MacssWeb.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tass {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tass() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MacssWeb.Resources.Tass", typeof(Tass).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   DOSS連携データ作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DossDataCreateMainTitle {
            get {
                return ResourceManager.GetString("DossDataCreateMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOSS連携データ詳細 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DossDataDetailsMainTitle {
            get {
                return ResourceManager.GetString("DossDataDetailsMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全社基幹向け に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DossDataForAll {
            get {
                return ResourceManager.GetString("DossDataForAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   北関東支社向け に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DossDataForKitaKanto {
            get {
                return ResourceManager.GetString("DossDataForKitaKanto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOSS連携データ一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DossDataListMainTitle {
            get {
                return ResourceManager.GetString("DossDataListMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOSS連携データ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DossDataMainTitle {
            get {
                return ResourceManager.GetString("DossDataMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TMS用出荷実績データ作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipmentResultsForTMSCreateMainTitle {
            get {
                return ResourceManager.GetString("ShipmentResultsForTMSCreateMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TMS用出荷実績詳細 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipmentResultsForTMSDetailsMainTitle {
            get {
                return ResourceManager.GetString("ShipmentResultsForTMSDetailsMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TMS用出荷実績一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipmentResultsForTMSListMainTitle {
            get {
                return ResourceManager.GetString("ShipmentResultsForTMSListMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TMS用出荷実績 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipmentResultsForTMSMainTitle {
            get {
                return ResourceManager.GetString("ShipmentResultsForTMSMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TMS用運賃データ作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShippingCostForTMSCreateMainTitle {
            get {
                return ResourceManager.GetString("ShippingCostForTMSCreateMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TMS用運賃データ一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShippingCostForTMSListMainTitle {
            get {
                return ResourceManager.GetString("ShippingCostForTMSListMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TMS用運賃データ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShippingCostForTMSMainTitle {
            get {
                return ResourceManager.GetString("ShippingCostForTMSMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TMS確定データ登録 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TMSFixedDataCreateDataMainTitle {
            get {
                return ResourceManager.GetString("TMSFixedDataCreateDataMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TMS確定データ詳細 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TMSFixedDataDetailMainTitle {
            get {
                return ResourceManager.GetString("TMSFixedDataDetailMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TMS作業依頼データ更新 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TMSFixedDataEditMainTitle {
            get {
                return ResourceManager.GetString("TMSFixedDataEditMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TMS確定データ一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TMSFixedDataListMainTitle {
            get {
                return ResourceManager.GetString("TMSFixedDataListMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TMS確定データ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TMSFixedDataMainTitle {
            get {
                return ResourceManager.GetString("TMSFixedDataMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TMSデータアップロード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TMSFixedDataUploadMainTitle {
            get {
                return ResourceManager.GetString("TMSFixedDataUploadMainTitle", resourceCulture);
            }
        }
    }
}
