//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MacssWeb.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Title {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Title() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MacssWeb.Resources.Title", typeof(Title).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   登録確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateConfirm {
            get {
                return ResourceManager.GetString("CreateConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   部門コード検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DepartmentCodeSearchDialog {
            get {
                return ResourceManager.GetString("DepartmentCodeSearchDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditConfirm {
            get {
                return ResourceManager.GetString("EditConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実行確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExecConfirm {
            get {
                return ResourceManager.GetString("ExecConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メール送信確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MailSendConfirm {
            get {
                return ResourceManager.GetString("MailSendConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   遷移確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransitionConfirm {
            get {
                return ResourceManager.GetString("TransitionConfirm", resourceCulture);
            }
        }
    }
}
