// <auto-generated />
namespace WebDevelopmentTemplate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class set_defaultvalue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(set_defaultvalue));
        
        string IMigrationMetadata.Id
        {
            get { return "201811290433076_set_defaultvalue"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
