// <auto-generated />
namespace Macss.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class create_table2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_table2));
        
        string IMigrationMetadata.Id
        {
            get { return "201903060029081_create_table2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
