// <auto-generated />
namespace Macss.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class create_table18 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_table18));
        
        string IMigrationMetadata.Id
        {
            get { return "201906260454451_create_table18"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
