//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスによって ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションを付けて
    // /str を使用するか、または Visual Studio プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   このクラスで使用されるキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Message", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   システムエラーが発生しました。管理者にお問い合わせください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE001 {
            get {
                return ResourceManager.GetString("CE001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}の出力に失敗しました。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE002 {
            get {
                return ResourceManager.GetString("CE002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データベース接続に失敗しました。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE003 {
            get {
                return ResourceManager.GetString("CE003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データベースへの接続情報がありません。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE004 {
            get {
                return ResourceManager.GetString("CE004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}の登録に失敗しました。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE005 {
            get {
                return ResourceManager.GetString("CE005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}の更新に失敗しました。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE006 {
            get {
                return ResourceManager.GetString("CE006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}の削除に失敗しました。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE007 {
            get {
                return ResourceManager.GetString("CE007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理の呼出しに失敗しました。|{0} に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE008 {
            get {
                return ResourceManager.GetString("CE008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}の取込に失敗しました。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE009 {
            get {
                return ResourceManager.GetString("CE009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}処理に失敗しました。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE010 {
            get {
                return ResourceManager.GetString("CE010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}データ{1}に失敗しました。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE011 {
            get {
                return ResourceManager.GetString("CE011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}処理中にエラーが発生しました。{1} に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE012 {
            get {
                return ResourceManager.GetString("CE012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   システムエラーが発生しました。管理者にお問合せください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE013 {
            get {
                return ResourceManager.GetString("CE013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在、システムが大変混み合っております。ご迷惑をお掛けいたしますが、しばらく時間をおいてからアクセスしてください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE014 {
            get {
                return ResourceManager.GetString("CE014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不正な値が送信されました。入力値を確認してください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE015 {
            get {
                return ResourceManager.GetString("CE015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   セッション情報の有効期限が切れました。再度、処理をやり直してください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE016 {
            get {
                return ResourceManager.GetString("CE016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイムアウトしました。再度ログインを行ってください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE017 {
            get {
                return ResourceManager.GetString("CE017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   他の端末で更新されました。再度検索し、更新処理を行ってください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE018 {
            get {
                return ResourceManager.GetString("CE018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象のデータがありません。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE019 {
            get {
                return ResourceManager.GetString("CE019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データ件数が{0}件を超えています。検索条件を指定して、再度処理を行ってください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE020 {
            get {
                return ResourceManager.GetString("CE020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示対象となるデータが存在しません。情報が削除された可能性があります。&lt;br/&gt;再度、TOP画面よりやり直してください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE021 {
            get {
                return ResourceManager.GetString("CE021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   権限がありません。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE022 {
            get {
                return ResourceManager.GetString("CE022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この機能は現在利用できません。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE023 {
            get {
                return ResourceManager.GetString("CE023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログインできません。ユーザＩＤまたはパスワードに誤りがあります。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE024 {
            get {
                return ResourceManager.GetString("CE024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログインされていません。ログイン画面より再度、ログインしてください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE025 {
            get {
                return ResourceManager.GetString("CE025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   旧パスワードに誤りがあるため、パスワードの変更ができません。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE026 {
            get {
                return ResourceManager.GetString("CE026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新パスワードが一致しません。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE027 {
            get {
                return ResourceManager.GetString("CE027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワードとパスワード（再入力）が一致しません。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE028 {
            get {
                return ResourceManager.GetString("CE028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アカウントロックされているためログインできません。管理者へお問合せください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE029 {
            get {
                return ResourceManager.GetString("CE029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}文字以内で入力してください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE030 {
            get {
                return ResourceManager.GetString("CE030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}を入力してください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE031 {
            get {
                return ResourceManager.GetString("CE031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}文字以上{2}以内で入力してください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE032 {
            get {
                return ResourceManager.GetString("CE032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}に{1}できません。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE033 {
            get {
                return ResourceManager.GetString("CE033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}に誤りがあります。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE034 {
            get {
                return ResourceManager.GetString("CE034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が一致しません。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE035 {
            get {
                return ResourceManager.GetString("CE035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が設定されていません。{1}してください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE036 {
            get {
                return ResourceManager.GetString("CE036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}に存在しない{1}が設定されています。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE037 {
            get {
                return ResourceManager.GetString("CE037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}の中で１つのみ{1}を設定してください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE038 {
            get {
                return ResourceManager.GetString("CE038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が選択されていません。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE039 {
            get {
                return ResourceManager.GetString("CE039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}から{2}の範囲内で入力してください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE040 {
            get {
                return ResourceManager.GetString("CE040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が存在します。{1}できません。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE041 {
            get {
                return ResourceManager.GetString("CE041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}に{1}はできません。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE042 {
            get {
                return ResourceManager.GetString("CE042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}：　半角数字を入力してください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE043 {
            get {
                return ResourceManager.GetString("CE043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}：　日付の入力に誤りがあります。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE044 {
            get {
                return ResourceManager.GetString("CE044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}：　必須項目を入力してください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE045 {
            get {
                return ResourceManager.GetString("CE045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   桁数オーバーです。（{0}文字以内で入力してください。）【{1}】 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE046 {
            get {
                return ResourceManager.GetString("CE046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   範囲外の値が指定されました。（{0}から{1}の数値を指定してください。）【{2}】 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE047 {
            get {
                return ResourceManager.GetString("CE047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}：　ひらがなのみで入力してください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE048 {
            get {
                return ResourceManager.GetString("CE048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォーマットが正しくありません。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE049 {
            get {
                return ResourceManager.GetString("CE049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}に{1}が紐付いているため削除できません。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE050 {
            get {
                return ResourceManager.GetString("CE050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}：　入力形式が正しくありません。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE051 {
            get {
                return ResourceManager.GetString("CE051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}：　{1}文字以内で入力してください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE052 {
            get {
                return ResourceManager.GetString("CE052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}：　取込項目がありません。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE053 {
            get {
                return ResourceManager.GetString("CE053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルを選択してください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE054 {
            get {
                return ResourceManager.GetString("CE054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は必須です。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE055 {
            get {
                return ResourceManager.GetString("CE055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {1}文字以内で入力してください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE056 {
            get {
                return ResourceManager.GetString("CE056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が重複しています。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE057 {
            get {
                return ResourceManager.GetString("CE057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が存在するため、{1}できません。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE058 {
            get {
                return ResourceManager.GetString("CE058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新対象データは存在しません。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE059 {
            get {
                return ResourceManager.GetString("CE059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録対象データは既に存在します。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE060 {
            get {
                return ResourceManager.GetString("CE060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}：　半角英数字を入力してください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE061 {
            get {
                return ResourceManager.GetString("CE061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}：　半角数字（ハイフン付き）を入力してください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE062 {
            get {
                return ResourceManager.GetString("CE062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}：　半角カナを入力してください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE063 {
            get {
                return ResourceManager.GetString("CE063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}：　半角文字を入力してください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE064 {
            get {
                return ResourceManager.GetString("CE064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除対象データは存在しません。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE065 {
            get {
                return ResourceManager.GetString("CE065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}：　入力してください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE066 {
            get {
                return ResourceManager.GetString("CE066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}：　マスタに存在しない{1}が設定されています。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE067 {
            get {
                return ResourceManager.GetString("CE067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}：　{1}してください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE068 {
            get {
                return ResourceManager.GetString("CE068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}：　{1}。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE069 {
            get {
                return ResourceManager.GetString("CE069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}：　誤りがあります。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE070 {
            get {
                return ResourceManager.GetString("CE070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}：　{1}文字以上{2}以内で入力してください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE071 {
            get {
                return ResourceManager.GetString("CE071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}：　半角英数字を入力してください。(半角小文字英字不可) に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE072 {
            get {
                return ResourceManager.GetString("CE072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}：　データベースと型が異なります。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE073 {
            get {
                return ResourceManager.GetString("CE073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {1}文字で入力してください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE074 {
            get {
                return ResourceManager.GetString("CE074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索結果がありません。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE075 {
            get {
                return ResourceManager.GetString("CE075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前月分のデータが退避されていません。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE100 {
            get {
                return ResourceManager.GetString("CE100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   末締処理が実行中です に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE101 {
            get {
                return ResourceManager.GetString("CE101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   退避済のため実行できません に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE102 {
            get {
                return ResourceManager.GetString("CE102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   該当ファイルがありません に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE103 {
            get {
                return ResourceManager.GetString("CE103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルの退避に失敗しました。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE104 {
            get {
                return ResourceManager.GetString("CE104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品番コード{0}：　製品マスタに重複するデータが存在します。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE105 {
            get {
                return ResourceManager.GetString("CE105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   締処理実行中のため退避処理は行えません に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE106 {
            get {
                return ResourceManager.GetString("CE106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   退避処理完了済です に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE107 {
            get {
                return ResourceManager.GetString("CE107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   締処理が異常終了しています に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE108 {
            get {
                return ResourceManager.GetString("CE108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}：　全角文字を入力してください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE109 {
            get {
                return ResourceManager.GetString("CE109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全角文字を入力。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE110 {
            get {
                return ResourceManager.GetString("CE110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   半角文字を入力。(小文字英字不可) に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE111 {
            get {
                return ResourceManager.GetString("CE111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   半角カナを入力。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE112 {
            get {
                return ResourceManager.GetString("CE112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   半角文字を入力。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE113 {
            get {
                return ResourceManager.GetString("CE113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   半角数字を入力。(ﾊｲﾌﾝ,ｶｯｺ可) に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE114 {
            get {
                return ResourceManager.GetString("CE114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   半角数字を入力。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE115 {
            get {
                return ResourceManager.GetString("CE115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   半角英数字を入力。(半角小文字英字不可) に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE116 {
            get {
                return ResourceManager.GetString("CE116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在と同じパスワードには変更できません。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE117 {
            get {
                return ResourceManager.GetString("CE117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【Ｈ】半角文字を入力。(小文字英字不可)　 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE118 {
            get {
                return ResourceManager.GetString("CE118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【ｉ】半角文字を入力。(小文字英字不可)　 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE119 {
            get {
                return ResourceManager.GetString("CE119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【Ｍ】半角文字を入力。(小文字英字不可)　 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE120 {
            get {
                return ResourceManager.GetString("CE120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【Ｐ】半角文字を入力。(小文字英字不可)　 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE121 {
            get {
                return ResourceManager.GetString("CE121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【集】半角文字を入力。(小文字英字不可)　 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE122 {
            get {
                return ResourceManager.GetString("CE122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【構】半角文字を入力。(小文字英字不可)　 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE123 {
            get {
                return ResourceManager.GetString("CE123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【Ｙ】半角文字を入力。(小文字英字不可)　 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE124 {
            get {
                return ResourceManager.GetString("CE124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【半】半角文字を入力。(小文字英字不可)　 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE125 {
            get {
                return ResourceManager.GetString("CE125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【長】半角文字を入力。(小文字英字不可)　 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE126 {
            get {
                return ResourceManager.GetString("CE126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【在】半角文字を入力。(小文字英字不可)　 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE127 {
            get {
                return ResourceManager.GetString("CE127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【需】半角文字を入力。(小文字英字不可)　 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE128 {
            get {
                return ResourceManager.GetString("CE128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【顧】半角文字を入力。(小文字英字不可)　 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE129 {
            get {
                return ResourceManager.GetString("CE129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【得】半角文字を入力。(小文字英字不可)　 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE130 {
            get {
                return ResourceManager.GetString("CE130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【ブ】半角文字を入力。(小文字英字不可)　 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE131 {
            get {
                return ResourceManager.GetString("CE131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【基】半角文字を入力。(小文字英字不可)　 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE132 {
            get {
                return ResourceManager.GetString("CE132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   　全角文字を入力。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CE133 {
            get {
                return ResourceManager.GetString("CE133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理が正常に終了しました。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CI001 {
            get {
                return ResourceManager.GetString("CI001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新が完了しました。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CI002 {
            get {
                return ResourceManager.GetString("CI002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録が完了しました。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CI003 {
            get {
                return ResourceManager.GetString("CI003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除が完了しました。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CI004 {
            get {
                return ResourceManager.GetString("CI004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}処理を中止しました。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CI005 {
            get {
                return ResourceManager.GetString("CI005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}処理が終了しました。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CI006 {
            get {
                return ResourceManager.GetString("CI006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   退避処理が完了しました。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CI007 {
            get {
                return ResourceManager.GetString("CI007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了します。よろしいですか？ に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CQ001 {
            get {
                return ResourceManager.GetString("CQ001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実行します。よろしいですか？ に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CQ002 {
            get {
                return ResourceManager.GetString("CQ002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   印刷します。よろしいですか？ に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CQ003 {
            get {
                return ResourceManager.GetString("CQ003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録します。よろしいですか？ に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CQ004 {
            get {
                return ResourceManager.GetString("CQ004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新します。よろしいですか？ に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CQ005 {
            get {
                return ResourceManager.GetString("CQ005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除します。よろしいですか？ に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CQ006 {
            get {
                return ResourceManager.GetString("CQ006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   既に{0}が存在します。上書きしてよろしいですか？ に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CQ007 {
            get {
                return ResourceManager.GetString("CQ007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}を作成します。よろしいですか？ に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CQ008 {
            get {
                return ResourceManager.GetString("CQ008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クリアします。入力された内容がクリアされます。よろしいですか？ に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CQ009 {
            get {
                return ResourceManager.GetString("CQ009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセルします。入力された内容がクリアされます。よろしいですか？ に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CQ010 {
            get {
                return ResourceManager.GetString("CQ010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力内容は破棄されます。よろしいですか？ に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CQ011 {
            get {
                return ResourceManager.GetString("CQ011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了します。登録／更新していない内容は破棄されます。よろしいですか？ に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CQ012 {
            get {
                return ResourceManager.GetString("CQ012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力内容を保存しますか？ に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CQ013 {
            get {
                return ResourceManager.GetString("CQ013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画面を移動します。内容が破棄される場合もあります。よろしいですか？ に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string CQ014 {
            get {
                return ResourceManager.GetString("CQ014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アカウントがロックされています。管理者にお問い合わせください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME001 {
            get {
                return ResourceManager.GetString("ME001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一致するユーザーが見つかりません。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME002 {
            get {
                return ResourceManager.GetString("ME002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規パスワードと確認用パスワードが異なります。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string ME003 {
            get {
                return ResourceManager.GetString("ME003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワードの有効期限が切れています。パスワードの変更をお願いします。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        internal static string MW001 {
            get {
                return ResourceManager.GetString("MW001", resourceCulture);
            }
        }
    }
}
